#!/usr/bin/env bash
spacer='----------------------------------------------------------------'

# Error handling
# http://stackoverflow.com/questions/2870992/automatic-exit-from-bash-shell-script-on-error
abort() {
	echo "ERROR: Setup was interrupted"
	exit 1
}

trap 'abort' 0

# Check that user is not root
if [[ "${EUID}" == "0" ]]; then
	echo "Please call this script as a regular user."
	exit 1
fi

# Determine absolute path
if [[ ! -d "${abs_path}" ]]; then
	abs_path="${BASH_SOURCE[0]}"

	if [ -h "${abs_path}" ]; then
		while [ -h "${abs_path}" ]; do
			abs_path=$(readlink "${abs_path}")
		done
	fi

	pushd . >/dev/null
	cd $(dirname "${abs_path}") >/dev/null
	abs_path=$(pwd)
	popd >/dev/null
fi

# Source scripts
source script/filesystem.sh
source script/distro.sh
source script/flags.sh
source script/package.sh

# This function installs a dotfile. It needs two parameters; the path to the dotfile to be
# installed, and the link name to use when installing.
link_to() {
	local source="${1}"
	local target="${2}"

	echo "- '${source}' -> '${target}'"

	# Check for required params
	[[ -z "${source}" ]] && echo "Error linking: Source path is empty" && return 1
	[[ -z "${target}" ]] && echo "Error linking: Target path is empty" && return 1

	# Check that dotfile exists
	if [[ ! -e "${source}" ]]; then
		ls -la "${source}"
		echo "Error creating link: The specified file or directory '${source}' does not exist"
		return 1
	fi

	# Check for existing item at ${target}
	if [[ -w "${target}" ]]; then
		if [[ -f "${target}" ]] || [[ -d "${target}" ]]; then
			# File or folder
			mv "${target}" "${target}.old"
		else
			# Link
			rm -f "${target}"
		fi
		# Create link
		ln -s "${source}" "${target}"
	fi
	return 0
}

determine_distro

echo "
Starting setup for '${distro}' in '${HOME}'"
echo "${spacer}"

parse_flags

if [[ "${NO_DEPENDENCIES}" != "true" ]]; then
	echo "
    Installing dependencies:"
	echo "${spacer}"

	# Refresh repos
	package sync

	# Install dependencies
	package git
	package curl
	package bash-completion
	package yaourt

	echo "
Done installing dependencies
    "
fi

# Create profile
echo '
Linking files'
echo "${spacer}"
link_to "${abs_path}/bash/.bash_profile" "${HOME}/.bash_profile"
link_to "${abs_path}/bash/.bashrc" "${HOME}/.bashrc"
link_to "${abs_path}/bash/.bash_logout" "${HOME}/.bash_logout"
source "${abs_path}/bash/.bash_profile"

# julia
link_to "${abs_path}/julia/.juliarc.jl" "${HOME}/.juliarc.jl"

# vim
link_to "${abs_path}/vim/.vimrc" "${HOME}/.vimrc"

# tmux
link_to "${abs_path}/tmux/.tmux.conf" "${HOME}/.tmux.conf"

source "${abs_path}/bash/.bash_profile"

if [[ "${NO_XORG}" != "true" ]]; then
	# xorg
	link_to "${abs_path}/xorg/.xinitrc" "${HOME}/.xinitrc"
	link_to "${abs_path}/xorg/.xprofile" "${HOME}/.xprofile"

	# vscode
	mkdir -p "${HOME}/.config/Code/User/snippets"
	link_to "${abs_path}/vscode/snippets" "${HOME}/.config/Code/User/snippets"
	link_to "${abs_path}/vscode/settings.json" "${HOME}/.config/Code/User/settings.json"

	# vscode insiders
	mkdir -p "${HOME}/.config/Code - Insiders/User/snippets"
	link_to "${abs_path}/vscode/snippets" "${HOME}/.config/Code - Insiders/User/snippets"
	link_to "${abs_path}/vscode/settings.json" "${HOME}/.config/Code - Insiders/User/settings.json"

	# [[ -e "${HOME}/.config/plasma-workspace/env/xprofile.sh" ]] && rm -f "${HOME}/.config/plasma-workspace/env/xprofile.sh"
	# touch "${HOME}/.config/plasma-workspace/env/xprofile.sh"
	# chmod +x "${HOME}/.config/plasma-workspace/env/xprofile.sh"

	# Generate xprofile file
	# mkdir -p "${HOME}/.config/plasma-workspace/env"
	# echo '#!/usr/bin/env bash' >"${HOME}/.config/plasma-workspace/env/xprofile.sh"
	# echo '# generated by dotfiles/setup.sh' >>"${HOME}/.config/plasma-workspace/env/xprofile.sh"
	# echo >>"${HOME}/.config/plasma-workspace/env/xprofile.sh"
	# echo 'source ~/.bashenv' >>"${HOME}/.config/plasma-workspace/env/xprofile.sh"
	# echo >>"${HOME}/.config/plasma-workspace/env/xprofile.sh"
fi

trap : 0

echo '
Setup completed
'
