#!/usr/bin/env bash
ABS_PATH="${BASH_SOURCE[0]}"
if [ -h "${ABS_PATH}" ]; then
  while [ -h "${ABS_PATH}" ]; do
    ABS_PATH=`readlink "${ABS_PATH}"`
  done
fi
pushd . > /dev/null
cd `dirname ${ABS_PATH}` > /dev/null
ABS_PATH=`pwd`;
popd  > /dev/null

# Create symlinks
echo "Creating symlinks"

[[ -e "${HOME}/.bashrc" ]] && rm -f "${HOME}/.bashrc"
ln -s "${ABS_PATH}/bash/.bashrc" "${HOME}/.bashrc"

[[ -e "${HOME}/.bashenv" ]] && rm -f "${HOME}/.bashenv"
ln -s "${ABS_PATH}/bash/.bashenv" "${HOME}/.bashenv"

[[ -e "${HOME}/.bash_profile" ]] && rm -f "${HOME}/.bash_profile"
ln -s "${ABS_PATH}/bash/.bash_profile" "${HOME}/.bash_profile"

[[ -e "${HOME}/.bash_logout" ]] && rm -f "${HOME}/.bash_logout"
ln -s "${ABS_PATH}/bash/.bash_logout" "${HOME}/.bash_logout"

[[ -e "${HOME}/.tmux.conf" ]] && rm -f "${HOME}/.tmux.conf"
ln -s "${ABS_PATH}/tmux/.tmux.conf" "${HOME}/.tmux.conf"

[[ -e "${HOME}/.vimrc" ]] && rm -f "${HOME}/.vimrc"
ln -s "${ABS_PATH}/vim/.vimrc" "${HOME}/.vimrc"

[[ -e "${HOME}/.xprofile" ]] && rm -f "${HOME}/.xprofile"
ln -s "${ABS_PATH}/xorg/.xprofile" "${HOME}/.xprofile"

[[ -e "${HOME}/.xinitrc" ]] && rm -f "${HOME}/.xinitrc"
ln -s "${ABS_PATH}/xorg/.xinitrc" "${HOME}/.xinitrc"

# Create KDE5 session from bash profile
echo "Add env to KDE5 session"

# Delete any existing session scripts
[[ -e "${HOME}/.config/plasma-workspace/env/" ]] || mkdir -p "${HOME}/.config/plasma-workspace/env/"
[[ -e "${HOME}/.config/plasma-workspace/env/xprofile.sh" ]] && rm -f "${HOME}/.config/plasma-workspace/env/xprofile.sh"

# Generate bash script
echo '#!/usr/bin/env bash' > "${HOME}/.config/plasma-workspace/env/xprofile.sh"
echo '# generated by dotfiles/setup.sh' >> "${HOME}/.config/plasma-workspace/env/xprofile.sh"
echo >> "${HOME}/.config/plasma-workspace/env/xprofile.sh"
echo "source ~/.bashenv" >> "${HOME}/.config/plasma-workspace/env/xprofile.sh"

# Done!
echo "All done."
